In [1]:
#Problem1:

import numpy as np

x = np.array([1, 2, 3, 4, 5])
n = 3
print(np.vander(x, n))
print(x**n)
arr = []
newArray = np.column_stack([x**(n-i-1) for i in range(n)])

c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\numpy\.libs\libopenblas.xwydx2ikjw2nmtwsfyngfuwkqu3lytcz.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
[  1   8  27  64 125]


In [2]:
#Problem 2:

def moving_window(seq, k):
    final = []
    for i in range(len(seq)-k+1):
        final.append(np.round(np.mean([seq[i+m] for m in range(k)]), 2))
    return final


print(moving_window([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3))

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
